CREATE TABLE Orders (
	OrderID		INT		NOT NULL IDENTITY,
	ClientID	INT		NOT NULL,
	BookingDate	DATE	NOT NULL,

	CONSTRAINT PK_Orders PRIMARY KEY CLUSTERED (OrderID ASC)
)

ALTER TABLE Orders
ADD CONSTRAINT FK_Orders_Clients
FOREIGN KEY (ClientID) REFERENCES Clients (ClientID)